version: '3.9'
services:
  db:
  #İşlem 2 :  Mariadb nin parametre değerini aşağıdaki şekilde yapınız.
    image: bitnami/mariadb:latest
    environment:
      - MYSQL_USER=YAM428
      - MYSQL_PASSWORD=030119064
      - MYSQL_DATABASE=final
    volumes:
      - db_data:/bitnami
      
#işlem 1-Drupal image name: bitnami/drupal:latest
  drupal:
    image: bitnami/drupal:latest
    ports:
      - 8080:8080
    environment:
      - DRUPAL_DATABASE_HOST=db
      - DRUPAL_DATABASE_PORT_NUMBER=3306
      - DRUPAL_DATABASE_NAME=final
      - DRUPAL_DATABASE_USER=YAM428
      - DRUPAL_DATABASE_PASSWORD=03011964
    volumes:
      - drupal_data:/bitnami
#İşlem 3 : Nginx servisine sizin alan adınızı tanımlayarak, sunucunun 80 nolu portundan web hizmeti vermesini sağlayınız
  webserver:
    image: nginx
    ports:
      - 443:80
    environment:
      - VIRTUAL_HOST=amiryfatima.me
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./certs:/etc/nginx/certs:ro
    depends_on:
      - drupal
#İşlem 4: Let's Encrypt hizmetini tanımlayarak web sunucunuzun SSL (443 portundan) hizmet vermesini sağlayın.
  certbot:
    image: certbot
    volumes:
      - ./certs:/etc/letsencrypt
    command: certonly --webroot --webroot-path=/etc/letsencrypt --email amiryfatima.me --agree-tos --no-eff-email --staging -d amiryfatima.me

volumes:
  db_data:
  drupal_data:
