version: '3.9'
services:
  db:
    image: bitnami/mariadb:latest
    environment:
      - MYSQL_USER=YAM428
      - MYSQL_PASSWORD=030119064
      - MYSQL_DATABASE=final
    volumes:
      - db_data:/bitnami

  drupal:
    image: bitnami/drupal:latest
    ports:
      - 8080:8080
    environment:
      - DRUPAL_DATABASE_HOST=db
      - DRUPAL_DATABASE_PORT_NUMBER=3306
      - DRUPAL_DATABASE_NAME=final
      - DRUPAL_DATABASE_USER=YAM428
      - DRUPAL_DATABASE_PASSWORD=<Sizin Öğrenci Numaranız>
    volumes:
      - drupal_data:/bitnami

  webserver:
    image: nginx
    ports:
      - 80:80
    environment:
      - VIRTUAL_HOST=<amiryfatima>
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./certs:/etc/nginx/certs:ro
    depends_on:
      - drupal

  certbot:
    image: certbot
    volumes:
      - ./certs:/etc/letsencrypt
    command: certonly --webroot --webroot-path=/etc/letsencrypt --email your_email@example.com --agree-tos --no-eff-email --staging -d amiryfatima

volumes:
  db_data:
  drupal_data:
